import { chromium } from 'playwright-core';
import { abrirMenuDoUsuario } from './lib-shell.mjs';
const BASE='http://localhost:5173';
const b=await chromium.launch({executablePath:'/usr/bin/google-chrome',headless:true});
const p=await(await b.newContext({viewport:{width:1280,height:900}})).newPage();
await p.goto(BASE+'/login',{waitUntil:'domcontentloaded'});
await p.fill('input[name=identifier]','admin@prefeitura-x.local');
await p.fill('input[type=password]','admin123');
await p.click('button[type=submit]');
await p.waitForURL(u=>!u.pathname.includes('login'),{timeout:30000});
await p.goto(BASE+'/tasks',{waitUntil:'domcontentloaded'});
await p.waitForTimeout(2500);
await abrirMenuDoUsuario(p);
console.log('menuitems:',JSON.stringify(await p.getByRole('menuitem').allInnerTexts()));
console.log('haspopup:',await p.locator('[role=menuitem][aria-haspopup=menu]').count());
await p.locator('[role=menuitem][aria-haspopup=menu]').first().click().catch(e=>console.log('clique falhou:',e.message.slice(0,60)));
await p.waitForTimeout(600);
console.log('radios:',JSON.stringify(await p.getByRole('menuitemradio').allInnerTexts()));
console.log('menus:',await p.locator('[role=menu]').count());
await b.close();
