// Componentes reais com API simulada: filtros globais/locais, header e responsividade.
import { build } from '../../node_modules/esbuild/lib/main.js';
import { chromium } from 'playwright-core';
import { mkdtemp, readdir, readFile } from 'node:fs/promises';
import { tmpdir } from 'node:os';
import { join, resolve } from 'node:path';
import assert from 'node:assert/strict';
const root=resolve(import.meta.dirname,'../..');
const out=await mkdtemp(join(tmpdir(),'septem-report-filters-'));
await build({stdin:{contents:`
import React from 'react';import {createRoot} from 'react-dom/client';
import {QueryClient,QueryClientProvider} from '@tanstack/react-query';
import {MemoryRouter} from 'react-router-dom';import {ConsultaViewPage} from './src/pages/relatorios/ConsultaViewPage';
import {useSessionStore} from './src/stores/session';
useSessionStore.setState({accessToken:'fixture',status:'authenticated'});
window.print=()=>{window.printed=true;};
createRoot(document.getElementById('root')).render(<QueryClientProvider client={new QueryClient({defaultOptions:{queries:{retry:false}}})}><MemoryRouter initialEntries={['/reports/view?key=test']}><ConsultaViewPage/></MemoryRouter></QueryClientProvider>);`,resolveDir:root,loader:'tsx'},bundle:true,outfile:join(out,'bundle.js'),platform:'browser',format:'iife',tsconfig:join(root,'tsconfig.app.json'),loader:{'.css':'empty'},define:{'import.meta.env':'{}'}});
const definition={filters:[{id:'q',label:'Palavra-chave',type:'text',required:true,default:'inicial'},{id:'status',label:'Situação',type:'select',options:['Aberto','Fechado']},{id:'period',label:'Período',type:'date'},{id:'count',label:'Quantidade',type:'number'}]};
const result={generatedAt:'2026-09-24T12:00:00Z',fromCache:true,totalRows:2,blocks:[{id:'table',type:'table',title:'Pedidos',columns:[{key:'name',label:'Nome',visible:true,colType:'text'},{key:'amount',label:'Valor',visible:true,colType:'number'},{key:'date',label:'Data',visible:true,colType:'date'}],rows:[['João','10','2026-09-20'],['Maria','50','2026-09-24']],total:2,hasHiddenColumns:false}]};
const browser=await chromium.launch({executablePath:process.env.CHROME_BIN??'/Applications/Google Chrome.app/Contents/MacOS/Google Chrome',headless:true});
try { for(const width of [375,1280]) {
 const page=await browser.newPage({viewport:{width,height:900}});page.setDefaultTimeout(8000);
 const calls=[],errors=[];page.on('pageerror',e=>errors.push(e.message));
 await page.route('https://reports.test/**',route=>{
  const path=new URL(route.request().url()).pathname;
  if(!path.startsWith('/api/'))return route.fulfill({contentType:'text/html',body:'<div id="root"></div>'});
  if(path.endsWith('/run'))calls.push(route.request().postDataJSON());
  return route.fulfill({contentType:'application/json',body:JSON.stringify(path.endsWith('/run')?result:{key:'test',name:'Relatório de pedidos',definitionJson:JSON.stringify(definition)})});
 });
 await page.goto('https://reports.test/');
 for(const file of (await readdir(join(root,'dist/assets'))).filter(f=>f.endsWith('.css')))await page.addStyleTag({content:await readFile(join(root,'dist/assets',file),'utf8')});
 await page.addScriptTag({path:join(out,'bundle.js')});
 await page.getByText('João',{exact:true}).first().waitFor();
 const header=page.locator('header').first();
 assert.equal(await header.getByRole('button',{name:'Obter dados mais recentes'}).count(),1);
 await header.getByRole('button',{name:'Imprimir / PDF'}).click();assert.equal(await page.evaluate(()=>window.printed),true);
 const trigger=page.getByRole('button',{name:/^Filtros/});
 const triggerBounds=await trigger.boundingBox();assert.ok(triggerBounds.x<30);
 const stamp=await page.getByTestId('report-timestamp').boundingBox();assert.ok(Math.abs(stamp.x+stamp.width-(width-24))<2);
 if(width>=640)assert.ok(Math.abs(triggerBounds.y+triggerBounds.height/2-stamp.y-stamp.height/2)<2,'Timestamp centralizado verticalmente');
 await page.screenshot({path:join(out,`report-${width}.png`)});
 await trigger.click();const popup=page.getByTestId('report-filters');
 const choose=async label=>{if(width<640&&await popup.getByRole('button',{name:'Todos os filtros'}).isVisible())await popup.getByRole('button',{name:'Todos os filtros'}).click();await popup.getByRole('navigation').getByRole('button',{name:label,exact:true}).click();};
 await choose('Palavra-chave');await popup.getByRole('textbox',{name:'Palavra-chave',exact:true}).fill('teste');
 await page.waitForResponse(r=>r.url().endsWith('/run')&&r.request().postDataJSON().filters.q==='teste');
 await choose('Situação');await popup.getByLabel('Aberto',{exact:true}).check();
 await page.waitForResponse(r=>r.url().endsWith('/run')&&r.request().postDataJSON().filters.status==='Aberto');
 await choose('Período');await popup.getByLabel('Mínimo de Período').fill('2026-09-01');await popup.getByLabel('Máximo de Período').fill('2026-09-24');
 await page.waitForResponse(r=>r.url().endsWith('/run')&&r.request().postDataJSON().filters.period==='2026-09-01..2026-09-24');
 await choose('Pedidos · Valor');await popup.getByLabel('Mínimo de Pedidos · Valor').fill('20');
 await page.screenshot({path:join(out,`popover-${width}.png`)});
 const bounds=await popup.boundingBox();assert.ok(bounds.x>=0&&bounds.x+bounds.width<=width&&bounds.y+bounds.height<=900);
 await page.keyboard.press('Escape');await popup.waitFor({state:'hidden'});
 assert.equal(await page.getByRole('cell',{name:'João',exact:true}).first().isVisible(),false);
 assert.equal(await page.getByRole('cell',{name:'Maria',exact:true}).first().isVisible(),true);
 await page.getByRole('button',{name:'Remover filtro Pedidos · Valor',exact:true}).click();
 assert.equal(await page.getByRole('cell',{name:'João',exact:true}).first().isVisible(),true);
 await page.getByRole('button',{name:'Limpar filtros',exact:true}).click();
 assert.equal(await header.getByRole('button',{name:'Obter dados mais recentes'}).isDisabled(),true,'Obrigatório vazio impede atualização');
 await page.getByText('Preencha os filtros obrigatórios para atualizar o relatório.').waitFor();
 await trigger.click();await choose('Palavra-chave');await popup.getByRole('textbox',{name:'Palavra-chave',exact:true}).fill('final');await page.keyboard.press('Escape');
 await page.waitForResponse(r=>r.url().endsWith('/run')&&r.request().postDataJSON().filters.q==='final');
 await header.getByRole('button',{name:'Obter dados mais recentes'}).click();
 await page.waitForResponse(r=>r.url().endsWith('/run')&&r.request().postDataJSON().refresh===true);
 assert.equal(calls.at(-1).refresh,true);assert.deepEqual(calls.at(-1).filters,{q:'final'});
 assert.equal(await page.evaluate(()=>document.documentElement.scrollWidth>innerWidth),false,'Sem overflow');
 assert.deepEqual(errors,[]);await page.close();console.log(`PASS ${width}: filtros globais e locais, chips, ações e timestamp`);
 }}finally{await browser.close();}
console.log(`Capturas: ${out}`);
